services:
  http_a_wol:
    image: bumer32/http_a_wol
    container_name: http_a_wol

    environment:
      TARGET_MAC: "00:11:22:33:44:55"
      TARGET_IP: "192.168.0.100"
      SERVER_IP: 0.0.0.0
      SERVER_PORT: 8000
      SSH_USER: "user"
      SSH_PASSWORD: "password"
    network_mode: "host"
    restart: unless-stopped